[project]
name = "manim-factory"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ameer Arsala <ameer.arsala03@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
python = ">=3.12.8,<3.13"
manim = ">=0.19.0,<0.20"
